FROM apache/airflow:2.9.3-python3.10

USER root

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libdbus-1-3 \
    libxcb1 \
    libxkbcommon0 \
    libx11-6 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    psycopg2-binary==2.9.12 \
    playwright==1.51.0 \
    beautifulsoup4==4.13.3 \
    mlflow==3.12.0 \
    xgboost==3.2.0 \
    scikit-learn==1.7.2 \
    pandas==2.3.3 \
    requests==2.34.2

RUN playwright install chromium
